-- PalauSport RBAC: app_role enum, user_roles table, auth hook, and new-user trigger
-- Clients use palausport-reservation-ui; employees use PalauSport CRM.

-- Enum for application roles
create type public.app_role as enum ('client', 'employee');
-- user_roles: links auth.users to app roles
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  role public.app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles: client (reservation app) or employee (CRM).';
-- Grant supabase_auth_admin read access (required for the custom access token hook)
grant usage on schema public to supabase_auth_admin;
grant select on table public.user_roles to supabase_auth_admin;
revoke all on table public.user_roles from authenticated, anon, public;
-- Trigger: new signups default to 'client'
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_roles (user_id, role)
  values (new.id, 'client')
  on conflict (user_id, role) do nothing;
  return new;
end;
$$;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();
-- Custom Access Token Hook: add user_role claim to JWT
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  -- Fetch the user role from user_roles
  select role into user_role
  from public.user_roles
  where user_id = (event->>'user_id')::uuid;

  claims := event->'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role::text));
  else
    -- Fallback: default to client if no row (backward compatibility)
    claims := jsonb_set(claims, '{user_role}', '"client"');
  end if;

  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;
